openapi: 3.0.0
info:
  title: InsightFlow MCP Server API
  description: MCP (Model Context Protocol) server for managing projects, stacks, roadmaps, tasks, and subtasks via Supabase Edge Functions
  version: 1.0.0
  contact:
    email: support@insightflow.com
servers:
  - url: https://yoxuhgzmxmrzxzrxrlky.supabase.co/functions/v1/mcp-handler
    description: Supabase Edge Function (Production)
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase authentication token (anon key for /tools, user token for other endpoints)
  schemas:
    Tool:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        inputSchema:
          type: object
    MCPResponse:
      type: object
      properties:
        tool:
          type: string
        success:
          type: boolean
        result:
          type: object
        error:
          type: string
        message:
          type: string
paths:
  /tools:
    get:
      summary: Get available MCP tools
      description: Returns a list of all available MCP tools (public endpoint, requires anon key)
      operationId: getTools
      tags:
        - Tools
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of available tools
          content:
            application/json:
              schema:
                type: object
                properties:
                  tools:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tool'
        '401':
          description: Unauthorized
  /:
    post:
      summary: Execute MCP tool
      description: Execute any MCP tool by providing the tool name and parameters in the request body
      operationId: executeTool
      tags:
        - Tools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tool
              properties:
                tool:
                  type: string
                  description: Tool name (e.g., projects/list, projects/create, stacks/list, etc.)
                  example: projects/list
      responses:
        '200':
          description: Tool execution result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MCPResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '405':
          description: Method Not Allowed

